### ISSUE TITLE
TypeError: tmp.length is not a function

### ISSUE THREAD

**Issue by ToracX** [drumfreak/homebridge-tuya-colorlight#3]
Hey i keep getting this error.
You have any idea what to do?

**Comment by ToracX** [comment]
I fixed that one now. 

[2019-6-7 12:05:47] Homebridge is running on port 51826.
[2019-6-7 12:06:01] [Tuya Color Light - lamp3] ~~~   Payload: 
[2019-6-7 12:06:01] [Tuya Color Light - lamp3] ~~~   { gwId: '03462186ecfabc33079b', devId: '03462186ecfabc33079b' }
[2019-6-7 12:06:01] [Tuya Color Light - lamp3] ~~~   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Sending GET request: lamp3
[2019-6-7 12:06:01] [Tuya Color Light - lamp3] ~~~   getBrightness: 100
[2019-6-7 12:06:01] [Tuya Color Light - lamp3] ~~~   getSaturation: 100
[2019-6-7 12:06:01] [Tuya Color Light - lamp3] ~~~   GET HUE: 130
[2019-6-7 12:06:01] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 73.598
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Error GET result: lamp3
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   TUYA GET COLOR LIGHT POWER ERROR for lamp3 dps: 1
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   connect EHOSTUNREACH 192.168.178.59:6668
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   END TUYA GET COLOR LIGHT POWER ERROR ~~~  
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Error GET result: lamp3
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   BEGIN TUYA GET COLOR LIGHT STATUS ERROR ~~~  
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   Got Tuya Color Light device ERROR for lamp3
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   { Error: connect EHOSTUNREACH 192.168.178.59:6668
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.178.59',
  port: 6668 }
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   END TUYA GET COLOR POWER STATUS ERROR ~~~  
[2019-6-7 12:06:13] [Tuya Color Light - lamp3] ~~~   Error getting light status

Getting this now.  I keep getting connect EHOSTUNREACH 192.168.178.59:6668?
